"""Change default value for rating

Revision ID: 40aff76adfd5
Revises: 7c312e42fcca
Create Date: 2025-10-05 03:03:55.875785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40aff76adfd5'
down_revision: Union[str, Sequence[str], None] = '7c312e42fcca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###
