"""Change precision rating

Revision ID: 47a024ebab12
Revises: 59b8e991c783
Create Date: 2025-10-05 02:17:18.750578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a024ebab12'
down_revision: Union[str, Sequence[str], None] = '59b8e991c783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.NUMERIC(precision=1, scale=2),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.NUMERIC(precision=1, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
