"""Change default value for rating

Revision ID: 7c312e42fcca
Revises: 47a024ebab12
Create Date: 2025-10-05 03:03:08.734701

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7c312e42fcca'
down_revision: Union[str, Sequence[str], None] = '47a024ebab12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=3, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.Numeric(precision=3, scale=1),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
