"""Rating NOT nullable

Revision ID: 858cbb7d5a4f
Revises: 40aff76adfd5
Create Date: 2025-10-06 00:30:34.575326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858cbb7d5a4f'
down_revision: Union[str, Sequence[str], None] = '40aff76adfd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=True)
    # ### end Alembic commands ###
